version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "AIQubeCentaur"  # Changed from "OoSos"
    commit-message:
      prefix: "pip"
      include: "scope"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  # Changed from "monthly"
    open-pull-requests-limit: 10  # Changed from 5
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "AIQubeCentaur"
    commit-message:
      prefix: "github-actions"
      include: "scope"
